<div class="warper container-fluid">

    <div class="page-header">
      <h1>Cadastramento de Projetos</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
      <div class="col-md-12">
        <div class="btn-group btn-group-justified">
          <a role="button" class="btn btn-default" href="/projects/" >Projetos Cadastrados</a>
          <a role="button" class="btn btn-primary" href="/projects/create" >Cadastrar Novo Projeto</a>
        </div><br>
      </div>
    </div>

    <div class="tab-content">

      <div class="panel panel-default">
        <div class="panel-body">

            <form method="post" class="form-horizontal validator-form" action="/projects/new" accept-charset="utf8" enctype="multipart/form-data" novalidate="novalidate">
              <?php echo $form->render("security"); ?>

              <div class="row">

                <div class="col-md-6">
                  <label class="control-label">Título do Projeto</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("title"); ?>
                  </div>
                </div>

                <div class="col-md-3">
                  <label class="control-label">Categoria</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("type"); ?>
                  </div>
                </div>

                <div class="col-md-3">
                  <label class="control-label">Deadline</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("deadline"); ?>
                  </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-6">
                  <label class="control-label">Membros</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("members"); ?>
                  </div>
                </div>

                <div class="col-md-6">
                  <label class="control-label">Cliente</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("client"); ?>
                  </div>
                </div>

              </div>
              <div class="row">
                <div class="col-md-12">
                  <br>
                	<?php echo $form->render("description"); ?>
                </div>
              </div>

              <hr class="dotted">

              <div class="row">
                <div class="col-sm-12">
                  <button type="submit" class="btn btn-primary btn-lg pull-right" name="signup" value="Validate">Cadastrar</button>
                </div>
              </div>

            </form>

        </div>
      </div>

  </div>
</div>
