<div class="warper container-fluid">

    <div class="page-header">
      <h1>Alterações e Informações do Projeto</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
    </div>

    <div class="tab-content">

      <div class="panel panel-default">
        <div class="panel-body">


        </div>
      </div>

  </div>
</div>
