<div class="warper container-fluid">

    <div class="page-header">
      <h1><?php echo $project->title; ?></h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2">
        <div class="panel panel-default">
          <div class="panel-heading clean">Navegação</div>
          <div class="panel-body no-padd">
            <div class="list-group no-margn mail-nav">
              <a href="/projects" class="list-group-item">Projetos Cadastrados</a>
              <a href="/project/<?php echo $project->_; ?>/overview" class="list-group-item on">Visão Geral</a>
              <a href="/project/<?php echo $project->_; ?>/tasks"    class="list-group-item">Tarefas</a>
              <a href="/project/<?php echo $project->_; ?>/settings" class="list-group-item">Configurações</a>
              <a href="/project/<?php echo $project->_; ?>/feedback" class="list-group-item">Feedback</a>
              <a href="/project/<?php echo $project->_; ?>/invoices" class="list-group-item">Faturas</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-10">
        <div class="panel-body">

          <div class="row">
            <div class="col-lg-6 col-md-12">
              <div class="row">

                <div class="col-lg-6 col-md-6">
                  <div class="panel panel-info">
                      <div class="panel-body">
                        <strong>Criado:</strong> <?php echo (new \DateTime($project->created))->format("d-m-Y"); ?>
                        <hr>
                        <strong>Deadline:</strong> <?php echo (new \DateTime($project->deadline))->format("d-m-Y"); ?>
                        <hr>
                        <strong>Concluído:</strong> <?php echo ($project->finished != null ? (new \DateTime($project->finished))->format("d-m-Y") : "n/a"); ?>
                        <hr>
                        <strong>Cliente:</strong> <?php echo "{$project->firstname} {$project->lastname}".($project->fantasy ? " ( {$project->fantasy} ) " : ""); ?>
                      </div>
                    </div>
                </div>

                <div class="col-lg-6 col-md-6">
                  <div data-chart="/project/<?php echo $project->_; ?>/chart" style="height:250px;"></div>
                </div>

                <?php if($project->description): ?>
                <div class="col-lg-12 col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading">Descrição</div>
                    <div class="panel-body">
                      <?php echo $project->description; ?>
                    </div>
                  </div>
                </div>
                <?php endif; ?>

                <div class="col-lg-12 col-md-12">
                  <div class="panel panel-default">
                    <div class="panel-heading space-between">
                      Membros do Projeto
                      <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-ajax="/project/<?php echo $project->_; ?>/member/create" >
                        <span class="fa fa-plus"></span> Adicionar Membro
                      </button>
                    </div>
                      <table class="table table-striped no-margn">
                        <tbody>
                          <?php foreach ($members as $member): ?>
                            <tr>
                              <td class="avtar">
                                <img src="/assets/manager/images/avtar/<?php echo $member->image; ?>" alt="<?php echo $member->name; ?>" class="img-circle avtar" />
                              </td>
                              <td>
                                <?php echo $member->name; ?><br>
                                <span class="label label-default"><?php echo $member->department; ?></span>
                              </td>
                              <td>
                                <button type="button" class="btn btn-danger pull-right" data-toggle="modal" data-ajax="/project/<?php echo $project->_; ?>/member/remove/<?php echo $member->uid ;?>">
                                  <span class="fa fa-close"></span>
                                </button>
                              </td>
                            </tr>
                          <?php endforeach; ?>
                        </tbody>
                      </table>
                  </div>
                </div>

              </div>
            </div>
            <div class="col-lg-6 col-md-12 panel panel-default activities-list nicescroll" style="min-height: 653px">
                <ul class="timeline list-unstyled">
                  <?php
                    foreach($logs as $log):
                      switch ($log->action) {
                        case $this->logs->create : $l = [ 'class' => "success",  'icon' => "check",       'title' => "Criação"];     break;
                        case $this->logs->update : $l = [ 'class' => "primary",  'icon' => "retweet",     'title' => "Alteração"];   break;
                        case $this->logs->delete : $l = [ 'class' => "danger",   'icon' => "trash",       'title' => "Remoção"];     break;
                        case $this->logs->info   : $l = [ 'class' => "info",     'icon' => "info-circle", 'title' => "Informação"];  break;
                      }
                  ?>
                  <li class="clearfix">
                      <time class="tl-time">
                          <h3 class="text-<?php echo $l['class']; ?>"><?php echo $l['title']; ?></h3>
                          <p><?php echo (new \DateTime($log->date))->format("d-m-Y \a\s H:i"); ?></p>
                        </time>
                        <i class="fa fa-<?php echo $l['icon']; ?> bg-<?php echo $l['class']; ?> tl-icon text-white"></i>
                        <div class="tl-content">
                          <div class="panel panel-<?php echo $l['class']; ?>">
                                <div class="panel-body">
                                  <?php echo $log->description; ?>
                                </div>
                            </div>
                        </div>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
          </div>

        </div>
      </div>
    </div>

</div>

<div id="modal-results"></div>
