<div class="warper container-fluid">

    <div class="page-header">
      <h1><?php echo $project->title; ?></h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-sm-2">
        <div class="btn-group btn-group-justified">
          <a role="button" class="btn btn-warning" data-filter="1" >Abertos</a>
          <a role="button" class="btn btn-warning" data-filter="2" >Concluídos</a>
          <!-- <a role="button" class="btn btn-warning" data-filter="3" >Cancelados</a> -->
        </div>
        <hr class="sm">
        <button type="button" class="btn btn-success btn-block btn-circle" data-toggle="modal" data-ajax="/project/<?php echo $project->_; ?>/tasks/create">
          <span class="fa fa-plus"></span> Adicionar Tarefa
        </button>
        <hr class="sm">
        <div class="panel panel-default">
          <div class="panel-heading clean">Navegação</div>
          <div class="panel-body no-padd">
            <div class="list-group no-margn mail-nav">
              <a href="/projects" class="list-group-item">Projetos Cadastrados</a>
              <a href="/project/<?php echo $project->_; ?>/overview" class="list-group-item">Visão Geral</a>
              <a href="/project/<?php echo $project->_; ?>/tasks"    class="list-group-item on">Tarefas</a>
              <a href="/project/<?php echo $project->_; ?>/settings" class="list-group-item">Configurações</a>
              <a href="/project/<?php echo $project->_; ?>/feedback" class="list-group-item">Feedback</a>
              <a href="/project/<?php echo $project->_; ?>/invoices" class="list-group-item">Faturas</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-10">
            <div class="col-lg-12 col-md-12">
              <div class="panel panel-default">
                <div class="panel-heading">
                  <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
                </div>
                <table class="table table-striped no-margn">
                    <thead>
                      <tr>
                        <th>Tarefa</th>
                        <th>Deadline</th>
                        <th>Designado à</th>
                        <th>Status</th>
                        <th><i class="fa fa-gears"></i></th>
                      </tr>
                    </thead>
                    <tbody>
                      <?php foreach($tasks as $task): ?>
                        <tr data-searchable data-filter-index="<?php echo $task->status; ?>" >
                          <td><?php echo $task->title; ?></td>
                          <td>
                            <?php $label = ((new \DateTime("now")) > (new \DateTime($task->deadline)) ? "label-danger" : "label-primary"); ?>
                            <span class="label <?php echo $label; ?>"><?php echo (new \DateTime($task->deadline))->format("d-m-Y"); ?></span>
                          </td>
                          <td>
                            <img src="/assets/manager/images/avtar/<?php echo $task->image; ?>" alt="<?php echo $task->name; ?>" class="img-circle avtar" />
                            <?php echo $task->name; ?><br>
                          </td>
                          <td>
                            <?php $status = ($task->status == 1 ? ["danger","Aberto"] : ["success","Concluído"]);?>
                            <span class="label label-<?php echo $status[0];?>"><?php echo $status[1];?></span>
                          </td>
                          <td>
                            <form method="post" class="validator-form" novalidate="novalidate" action="/project/<?php echo $project->_; ?>/tasks/remove/<?php echo $task->_; ?>">
                              <?php echo $form->render("security"); ?>
                              <div class="btn-group">
                                <button type="button" class="btn btn-info" data-toggle="modal" data-ajax="/project/<?php echo $project->_; ?>/tasks/view/<?php echo $task->_; ?>">
                                  <span class="fa fa-info-circle"></span>
                                  Info
                                </button>
                                <button type="button" class="btn btn-primary" data-toggle="modal" data-ajax="/project/<?php echo $project->_; ?>/tasks/modify/<?php echo $task->_; ?>">
                                  <span class="fa fa-pencil"></span>
                                  Editar
                                </button>
                                <button type="submit" class="btn btn-danger">
                                  <span class="fa fa-close"></span>
                                  Remover
                                </button>
                              </div>
                            </form>
                          </td>
                        </tr>
                      <?php endforeach; ?>
                    </tbody>
                  </table>
              </div>
            </div>
      </div>
    </div>

</div>

<div id="modal-results"></div>
