<div class="warper container-fluid">

  <div class="page-header">
    <h1>Configurações &mdash; Administradores</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="alert hidden" role="alert">
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <hr class="dotted">

  <div class="row">

    <div class="col-sm-3">

      <div class="panel panel-default">

        <div class="panel-heading clean">General</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/email" class="list-group-item">E-Mail</a>
            <a href="/settings/admin" class="list-group-item on">Administradores</a>
            <a href="/settings/server" class="list-group-item">Configurações do Servidor</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Equipe</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/team/permissions" class="list-group-item">Permissões</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Clientes</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/clients/permissions" class="list-group-item">Permissões</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Projetos</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/projects/" class="list-group-item">Work</a>
          </div>
        </div>

      </div>

    </div>

    <div class="col-sm-9">
        <div class="panel panel-default">
          <div class="panel-body">

  

          </div>

        </div>
      </div>

</div>
