<div class="warper container-fluid">

  <div class="page-header">
    <h1>Configurações &mdash; Servidor</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="alert hidden" role="alert">
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <hr class="dotted">

  <div class="row">

    <div class="col-sm-3">

      <div class="panel panel-default">

        <div class="panel-heading clean">General</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/email" class="list-group-item">E-Mail</a>
            <a href="/settings/admin" class="list-group-item">Administradores</a>
            <a href="/settings/server" class="list-group-item on">Configurações do Servidor</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Equipe</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/team/permissions" class="list-group-item">Permissões</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Clientes</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/clients/permissions" class="list-group-item">Permissões</a>
          </div>
        </div>

        <hr class="xs">

        <div class="panel-heading clean">Projetos</div>
        <div class="panel-body no-padd">
        	<div class="list-group no-margn mail-nav">
            <a href="/settings/projects/" class="list-group-item">Work</a>
          </div>
        </div>

      </div>

    </div>

    <div class="col-sm-9">
        <div class="panel panel-default">
          <div class="panel-body">

            <div class="alert alert-warning">
              <h4>Atenção</h4>
              Quais quer má configurações feitas aqui poderá afetar o funcionamento do sistema ,
              caso algum erro ocorra , edite as configurações manualmente em <strong>config/config.ini</strong>
            </div>

            <form method="post" class="form-horizontal validator-form" action="/settings/server/save" accept-charset="utf8" enctype="multipart/form-data" novalidate="novalidate">
              <?php echo $form->render("security"); ?>
              <div class="row">

                <div class="col-md-6">
                  <label class="control-label">Host</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("host"); ?>
                  </div>
                </div>

                <div class="col-md-6">
                  <label class="control-label">Username</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("username"); ?>
                  </div>
                </div>

                <div class="col-md-6">
                  <label class="control-label">Password</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("password"); ?>
                  </div>
                </div>

                <div class="col-md-6">
                  <label class="control-label">Database</label>
                  <div class="form-group has-feedback">
                    <?php echo $form->render("database"); ?>
                  </div>
                </div>

              </div>

              <hr class="dotted">

              <div class="row">
                <div class="col-sm-12">
                  <button type="submit" class="btn btn-primary btn-lg pull-right" name="signup" value="Validate">Salvar</button>
                </div>
              </div>
            </form>

          </div>

        </div>
      </div>

</div>
