<div class="warper container-fluid">

  <div class="page-header">
    <h1>Gerenciamento de Clientes</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div role="alert" class="alert fade in hidden">
        <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <div class="panel panel-default">
        <div class="panel-heading clean">Navegação</div>
        <div class="panel-body no-padd">
          <div class="list-group no-margn mail-nav">
            <a href="/clients" class="list-group-item on">Clientes Cadastrados</a>
            <a href="/clients/create" class="list-group-item">Cadastrar Cliente</a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10">
      <div class="panel panel-default table-responsive">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
            </div>
          </div>
        </div>
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th class="avtar"></th>
                <th>Responsável</th>
                <th>N &deg; Documento</th>
                <th>Domínio</th>
                <th>Telefone</th>
                <th><i class="fa fa-cogs"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($clients as $client): ?>
                <tr data-searchable >
                  <td><img src="/assets/manager/images/avtar/<?php echo $client->image; ?>" alt="<?php echo "{$client->firstname} {$client->lastname}"; ?>" class="img-circle avtar" /></td>
                    <td>
                      <?php echo "{$client->firstname} {$client->lastname}"; if($client->fantasy): ?>
                        <br><span class="label label-primary bigger-text"><?php echo $client->fantasy ;?></span>
                      <?php endif; ?>
                    </td>
                    <td><?php echo $client->document; ?></td>
                    <td><?php echo $client->domain; ?></td>
                    <td><?php echo $client->phone; ?></td>
                    <td>
                      <form method="post" class="validator-form" action="/client/remove/<?php echo $client->_ ;?>" novalidate="novalidate">
                        <div class="btn-group">
                          <button type="button" class="btn btn-info" data-toggle="modal" data-ajax="/client/view/<?php echo $client->_;?>">
                            <span class="fa fa-info-circle"></span>
                            Info
                          </button>
                          <button type="button" class="btn btn-primary" data-href="/client/modify/<?php echo $client->_ ;?>">
                            <span class="fa fa-pencil"></span>
                            Editar
                          </button>
                          <button type="submit" class="btn btn-danger">
                            <span class="fa fa-close"></span>
                            Remover
                          </button>
                        </div>
                        <?php echo $form->render("security"); ?>
                      </form>
                    </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

      </div>
    </div>
  </div>

</div>

<div id="modal-results"></div>
