<div class="warper container-fluid">

    <div class="page-header">
      <h1>Alteração de informações de Clientes</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2">
        <div class="panel panel-default">
          <div class="panel-heading clean">Navegação</div>
          <div class="panel-body no-padd">
            <div class="list-group no-margn mail-nav">
              <a href="/clients" class="list-group-item">Clientes Cadastrados</a>
              <a href="/clients/create" class="list-group-item">Cadastrar Cliente</a>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-10">

              <div class="panel panel-default">
                <div class="panel-body">
                  <form method="post" class="form-horizontal validator-form" action="/clients/update/<?php echo $uid; ?>" accept-charset="utf8" enctype="multipart/form-data" novalidate="novalidate">
                    <div class="row">

                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Nome do responsável</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("firstName"); ?>
                          </div>
                      </div>

                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Sobrenome do responsável</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("lastName"); ?>
                          </div>
                      </div>

                      <?php if($form->has("company")): ?>
                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Razão Social</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("company"); ?>
                          </div>
                      </div>
                      <?php endif; ?>

                      <?php if($form->has("fantasy")): ?>
                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Nome Fantasia</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("fantasy"); ?>
                          </div>
                      </div>
                      <?php endif; ?>

                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">N&deg; Documento</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("document"); ?>
                          </div>
                      </div>

                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Email</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("email"); ?>
                          </div>
                      </div>

                      <?php if($form->has("registration")): ?>
                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Inscrição Estadual</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("registration"); ?>
                          </div>
                      </div>
                      <?php endif; ?>

                      <?php if($form->has("role")): ?>
                      <div class="col-md-<?php echo $size; ?>">
                          <label class="control-label">Cargo</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("role"); ?>
                          </div>
                      </div>
                      <?php endif; ?>

                      <div class="col-md-3">
                          <label class="control-label">Telefone</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("phone"); ?>
                          </div>
                      </div>

                      <div class="col-md-3">
                          <label class="control-label">Celular</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("cellphone"); ?>
                          </div>
                      </div>

                      <div class="col-md-6">
                          <label class="control-label">Domínio</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("domain"); ?>
                          </div>
                      </div>

                    </div>

                    <hr class="dotted">

                    <div class="row">

                      <div class="col-md-4">
                          <label class="control-label">Endereço</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("address"); ?>
                          </div>
                      </div>

                      <div class="col-md-2">
                          <label class="control-label">Bairro</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("district"); ?>
                          </div>
                      </div>

                      <div class="col-md-2">
                          <label class="control-label">CEP</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("zip"); ?>
                          </div>
                      </div>

                      <div class="col-md-2">
                          <label class="control-label">Cidade</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("city"); ?>
                          </div>
                      </div>

                      <div class="col-md-2">
                          <label class="control-label">Estado (UF)</label>
                          <div class="form-group has-feedback">
                          <?php echo $form->render("state"); ?>
                          </div>
                      </div>

                    </div>

                    <hr class="dotted">

                    <div class="row">

                      <div class="col-md-4">
                          <label class="control-label">Imagem do Usuário</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("file"); ?>
                          </div>
                      </div>

                      <div class="col-md-4">
                          <label class="control-label">Nome de Usuário</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("username"); ?>
                          </div>
                      </div>

                      <div class="col-md-4">
                          <label class="control-label">Senha de Acesso</label>
                          <div class="form-group has-feedback">
                            <?php echo $form->render("password"); ?>
                          </div>
                      </div>

                    </div>

                    <?php if($form->has("contact_name[]")): ?>
                    <hr class="dotted">

                    <div data-clones>

                      <button type="button" class="btn btn-success btn-lg pull-right" data-add>
                        <span class="fa fa-plus"></span>
                        Contato
                      </button>
                      <h2>Contatos</h2>

                      <div data-clone-tpl>
                        <div class="row" data-clone >

                          <div class="col-md-2">
                              <label class="control-label">Nome Completo</label>
                              <div class="form-group has-feedback">
                                <?php echo $form->render("contact_name[]"); ?>
                              </div>
                          </div>

                          <div class="col-md-2">
                              <label class="control-label">Telefone</label>
                              <div class="form-group has-feedback">
                                <?php echo $form->render("contact_phone[]"); ?>
                              </div>
                          </div>

                          <div class="col-md-2">
                              <label class="control-label">Celular</label>
                              <div class="form-group has-feedback">
                                <?php echo $form->render("contact_cellphone[]"); ?>
                              </div>
                          </div>

                          <div class="col-md-2">
                              <label class="control-label">E-Mail</label>
                              <div class="form-group has-feedback">
                                <?php echo $form->render("contact_email[]"); ?>
                              </div>
                          </div>

                          <div class="col-md-3">
                              <label class="control-label">Área</label>
                              <div class="form-group has-feedback form-inline">
                                <?php echo $form->render("contact_area[]"); ?>
                                  <?php echo $form->render("security"); ?>
                                  <button type="button" class="btn btn-danger" data-remove >
                                    <span class="fa fa-close"></span>
                                  </button>
                              </div>
                          </div>

                        </div>
                      </div>

                      <?php if(count($contacts) > 0): foreach ($contacts as $contact):  ?>
                      <div class="row" data-clone >

                        <div class="col-md-2">
                            <label class="control-label">Nome Completo</label>
                            <div class="form-group has-feedback">
                              <input type="text" name="contact_name[]" class="form-control" value="<?php echo $contact->name; ?>">
                            </div>
                        </div>

                        <div class="col-md-2">
                            <label class="control-label">Telefone</label>
                            <div class="form-group has-feedback">
                              <input type="text" name="contact_phone[]" class="form-control" value="<?php echo $contact->phone; ?>">
                            </div>
                        </div>

                        <div class="col-md-2">
                            <label class="control-label">Celular</label>
                            <div class="form-group has-feedback">
                              <input type="text" name="contact_cellphone[]" class="form-control" value="<?php echo $contact->cellphone; ?>">
                            </div>
                        </div>

                        <div class="col-md-2">
                            <label class="control-label">E-Mail</label>
                            <div class="form-group has-feedback">
                              <input type="text" name="contact_email[]" class="form-control" value="<?php echo $contact->email; ?>">
                            </div>
                        </div>

                        <div class="col-md-3">
                            <label class="control-label">Área</label>
                            <div class="form-group has-feedback form-inline">
                              <input type="text" name="contact_area[]" class="form-control" value="<?php echo $contact->area; ?>">
                                <button type="button" class="btn btn-danger" data-remove >
                                  <span class="fa fa-close"></span>
                                </button>
                            </div>
                        </div>

                      </div>
                    <?php endforeach; endif; ?>
                  </div>
                  <?php endif;?>
                  <hr class="dotted">

                  <?php echo $form->render("security"); ?>

                  <div class="row">
                    <div class="col-sm-12">
                      <button type="submit" class="btn btn-primary btn-lg pull-right" name="signup" value="Validate">
                        Salvar Alterações
                      </button>
                    </div>
                  </div>

                </form>
              </div>
            </div>

      </div>
    </div>
