<div class="warper container-fluid">

  <div class="page-header">
    <h1>Tarefas Designadas</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="alert hidden" role="alert">
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
    <div class="col-md-10 col-sm-12">
      <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search ><br>
    </div>
    <div class="col-md-2 col-sm-12">
      <div class="btn-group btn-group-justified">
        <a role="button" class="btn btn-warning" data-filter="1" >Abertos</a>
        <a role="button" class="btn btn-warning" data-filter="2" >Concluídos</a>
      </div>
    </div>
  </div>
  <hr class="dotted">
  <div class="row">
    <div class="col-lg-12 col-md-12">
      <div class="panel panel-default">
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th>Deadline</th>
                <th>Projeto</th>
                <th>Tarefa</th>
                <th>Descrição</th>
                <th><i class="fa fa-gears"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach($tasks as $task): ?>
                <tr data-searchable data-filter-index="<?php echo $task->status; ?>" >
                  <td>
                    <?php $label = ((new \DateTime("now")) > (new \DateTime($task->deadline)) ? "label-danger" : "label-primary"); ?>
                    <span class="label <?php echo $label; ?>"><?php echo (new \DateTime($task->deadline))->format("d-m-Y"); ?></span>

                    <?php if( $task->status == 2 ): ?>
                      <span class="label label-primary"><?php echo (new \DateTime($task->completed))->format("d-m-Y"); ?></span>
                    <?php endif; ?>
                  </td>
                  <td><?php echo $task->project; ?></td>
                  <td><?php echo $task->title; ?></td>
                  <td><?php echo $task->description; ?></td>
                  <td>
                    <?php $action = ( $task->status == 1 ? 'close' : 'open' ); ?>
                    <form method="post" class="validator-form" action="/tasks/status/<?php echo "{$action}/{$task->_}"; ?>" novalidate="novalidate">
                      <?php echo $form->render("security"); ?>
                      <button type="submit" class="btn btn-<?php echo ( $task->status == 1 ? 'success' : 'danger' ); ?>">
                        <span class="fa fa-<?php echo ( $task->status == 1 ? 'check' : 'exchange' ); ?>"></span>
                      </button>
                    </form>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
      </div>
    </div>
  </div>

</div>
