<div class="warper container-fluid">

  <div class="page-header">
    <h1>Tarefas Designadas</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="alert hidden" role="alert">
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-10">
      <button type="button" class="btn btn-success btn-block btn-circle" data-toggle="modal" data-target="#create">
        <span class="fa fa-plus"></span> Adicionar Tarefa
      </button>
    </div>
  </div>

  <hr class="dotted">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default table-responsive">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-9">
              <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
            </div>
            <hr class="dotted hidden-md hidden-lg">
            <div class="col-md-3">
              <div class="btn-group btn-group-justified">
                <a role="button" class="btn btn-default" data-filter="1" >Abertos</a>
                <a role="button" class="btn btn-default" data-filter="2" >Concluídos</a>
                <!-- <a role="button" class="btn btn-warning" data-filter="3" >Cancelados</a> -->
              </div>
            </div>
          </div>
        </div>
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th>Deadline</th>
                <th>Projeto</th>
                <th>Tarefa</th>
                <th>Descrição</th>
                <th><i class="fa fa-gears"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach($tasks as $task): ?>
                <tr data-searchable data-filter-index="<?php echo $task->status; ?>" >
                  <td>
                    <?php $label = ((new \DateTime("now")) > (new \DateTime($task->deadline)) ? "label-danger" : "label-primary"); ?>
                    <span class="label <?php echo $label; ?>"><?php echo (new \DateTime($task->deadline))->format("d-m-Y"); ?></span>

                    <?php if( $task->status == 2 ): ?>
                      <span class="label label-primary"><?php echo (new \DateTime($task->completed))->format("d-m-Y"); ?></span>
                    <?php endif; ?>
                  </td>
                  <td><?php echo $task->project; ?></td>
                  <td><?php echo $task->title; ?></td>
                  <td><?php echo $task->description; ?></td>
                  <td>
                    <?php $action = ( $task->status == 1 ? 'close' : 'open' ); ?>
                    <form method="post" class="validator-form" action="/tasks/status/<?php echo "{$action}/{$task->_}"; ?>" novalidate="novalidate">
                      <?php echo $form->render("security"); ?>
                      <button type="submit" class="btn btn-<?php echo ( $task->status == 1 ? 'success' : 'danger' ); ?>">
                        <span class="fa fa-<?php echo ( $task->status == 1 ? 'check' : 'exchange' ); ?>"></span>
                      </button>
                    </form>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
      </div>
    </div>
  </div>

</div>

<!-- add task -->
<div class="modal fade" id="create" tabindex="-1" role="dialog" aria-labelledby="create" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="create">Adicionar Tarefa</h4>
      </div>

      <form method="post" class="form-horizontal validator-form" action="/tasks/new" accept-charset="utf8" enctype="multipart/form-data" novalidate="novalidate">
        <div class="modal-body">

          <div class="row">
            <div class="col-md-12">
              <div class="alert hidden" role="alert" id="createBox">
                <h4 id="title"></h4>
                <p id="desc"></p>
              </div>
            </div>
          </div>

          <?php echo $form->render("security"); ?>

          <div class="row">

            <div class="col-md-12">
              <label class="control-label">Título</label>
              <div class="form-group has-feedback">
                <?php echo $form->render("title"); ?>
              </div>
            </div>

            <div class="col-md-12">
              <label class="control-label">Descrição</label>
              <div class="form-group has-feedback">
                <?php echo $form->render("description"); ?>
              </div>
            </div>

          </div>
          <div class="row">

            <div class="col-md-12">
              <label class="control-label">Projeto Associado</label>
              <div class="form-group has-feedback">
                <?php echo $form->render("project"); ?>
              </div>
            </div>

            <div class="col-md-12">
              <label class="control-label">Deadline</label>
              <div class="form-group has-feedback">
                <?php echo $form->render("deadline"); ?>
              </div>
            </div>

          </div>
          <div class="row">
            <div class="col-md-12">
              <label class="control-label">Designado à</label>
              <div class="form-group has-feedback">
                <?php echo $form->render("assigned"); ?>
              </div>
            </div>
          </div>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
          <button type="submit" class="btn btn-primary">Cadastrar</button>
        </div>
      </form>
    </div>
  </div>
</div>
