<div class="warper container-fluid">

  <div class="page-header">
    <h1>Tarefas Designadas</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="alert hidden" role="alert">
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2 col-md-offset-10">
      <button type="button" class="btn btn-success btn-block btn-circle" data-toggle="modal" data-ajax="/task/create/">
        <span class="fa fa-plus"></span> Adicionar Tarefa
      </button>
    </div>
  </div>

  <hr class="dotted">
  <div class="row">
    <div class="col-md-12">
      <div class="panel panel-default table-responsive">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-9">
              <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
            </div>
            <hr class="dotted hidden-md hidden-lg">
            <div class="col-md-3">
              <div class="btn-group btn-group-justified">
                <a role="button" class="btn btn-default" data-filter="1" >Abertos</a>
                <a role="button" class="btn btn-default" data-filter="2" >Concluídos</a>
                <!-- <a role="button" class="btn btn-warning" data-filter="3" >Cancelados</a> -->
              </div>
            </div>
          </div>
        </div>
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th>Deadline</th>
                <th>Projeto</th>
                <th>Tarefa</th>
                <th>Descrição</th>
                <th><i class="fa fa-gears"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach($tasks as $task): ?>
                <tr data-searchable data-filter-index="<?php echo $task->status; ?>" >
                  <td>
                    <?php $label = ((new \DateTime("now")) > (new \DateTime($task->deadline)) ? "label-danger" : "label-primary"); ?>
                    <span class="label <?php echo $label; ?>"><?php echo (new \DateTime($task->deadline))->format("d-m-Y"); ?></span>

                    <?php if( $task->status == 2 ): ?>
                      <span class="label label-primary"><?php echo (new \DateTime($task->completed))->format("d-m-Y"); ?></span>
                    <?php endif; ?>
                  </td>
                  <td><?php echo $task->project; ?></td>
                  <td><?php echo $task->title; ?></td>
                  <td><?php echo $task->description; ?></td>
                  <td>
                    <?php $action = ( $task->status == 1 ? 'close' : 'open' ); ?>
                    <form method="post" class="validator-form" action="/tasks/status/<?php echo "{$action}/{$task->_}"; ?>" novalidate="novalidate">
                      <?php echo $form->render("security"); ?>
                      <?php if($task->status == 1): ?>
                        <div class="btn-group">
                          <button type="button" class="btn btn-info" data-toggle="modal" data-ajax="/task/view/<?php echo $task->_;?>">
                            <span class="fa fa-info-circle"></span>
                            Info
                          </button>
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-ajax="/task/update/<?php echo $task->_;?>">
                            <span class="fa fa-pencil"></span>
                            Editar
                          </button>
                          <button type="submit" class="btn btn-success">
                            <span class="fa fa-check"></span>
                            Concluír
                          </button>
                        </div>
                      <?php elseif($task->status == 2): ?>
                        <div class="btn-group">
                          <button type="button" class="btn btn-info" data-toggle="modal" data-ajax="/task/view/<?php echo $task->_;?>">
                            <span class="fa fa-info-circle"></span>
                            Info
                          </button>
                          <button type="button" class="btn btn-primary" data-toggle="modal" data-ajax="/task/update/<?php echo $task->_;?>">
                            <span class="fa fa-pencil"></span>
                            Editar
                          </button>
                          <button type="submit" class="btn btn-danger">
                            <span class="fa fa-exchange"></span>
                            Abrir
                          </button>
                        </div>
                      <?php endif; ?>
                    </form>
                  </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>
      </div>
    </div>
  </div>

</div>

<div id="modal-results"></div>
