<div class="warper container-fluid">

    <div class="page-header">
      <h1>Cadastramento de Equipe</h1>
    </div>

    <div class="row">
      <div class="col-md-12">
        <div role="alert" class="alert fade in hidden">
          <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
          <h4 id="title"></h4>
          <p id="desc"></p>
        </div>
      </div>
      <div class="col-md-12">
        <div class="btn-group btn-group-justified">
          <a role="button" class="btn btn-default" href="/team/" >Membros Cadastrados</a>
          <a role="button" class="btn btn-primary" href="/team/create" >Cadastrar Novo Membro</a>
          <a role="button" class="btn btn-default" href="/team/departments" >Departamentos</a>
        </div><br>
      </div>
    </div>

    <div class="tab-content">

      <div class="panel panel-default">
        <div class="panel-body">

            <form method="post" class="form-horizontal validator-form" action="/team/new" accept-charset="utf8" enctype="multipart/form-data" novalidate="novalidate">
              <?php echo $form->render("security"); ?>
              <div class="row">

                <div class="col-md-6">
                    <label class="control-label">Nome Completo</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("name"); ?>
                    </div>
                </div>

                <div class="col-md-6">
                    <label class="control-label">Email</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("email"); ?>
                    </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-6">
                    <label class="control-label">Telefone</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("phone"); ?>
                    </div>
                </div>

                <div class="col-md-6">
                    <label class="control-label">Departamento</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("department"); ?>
                    </div>
                </div>

              </div>
              <div class="row">

                <div class="col-md-6">
                    <label class="control-label">Permissão Interna</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("permission"); ?>
                    </div>
                </div>

                <div class="col-md-6">
                    <label class="control-label">Foto</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("image"); ?>
                    </div>
                </div>

              </div>

              <hr class="dotted">

              <div class="row">

                <div class="col-md-3">
                    <label class="control-label">Nome de Usuário</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("username"); ?>
                    </div>
                </div>

                <div class="clearfix"></div>

                <div class="col-md-3">
                    <label class="control-label">Senha de Acesso</label>
                    <div class="form-group has-feedback">
                      <?php echo $form->render("password"); ?>
                    </div>
                </div>

              </div>

              <hr class="dotted">

              <div class="row">
                <div class="col-sm-12">
                  <button type="submit" class="btn btn-primary btn-lg pull-right" name="signup" value="Validate">Cadastrar</button>
                </div>
              </div>

            </form>

        </div>
      </div>

  </div>
</div>
