<div class="warper container-fluid">

  <div class="page-header">
    <h1>Gerenciamento de Departamentos</h1>
  </div>

  <div class="row">
    <div class="col-md-2">
      <button type="button" class="btn btn-success btn-block btn-circle" data-toggle="modal" data-ajax="/team/department/create">
        <span class="fa fa-plus"></span> Adicionar Departamento
      </button>
      <hr class="dotted">
      <div class="panel panel-default">
        <div class="panel-heading clean">Navegação</div>
        <div class="panel-body no-padd">
          <div class="list-group no-margn mail-nav">
            <a href="/team" class="list-group-item">Membros Cadastrados</a>
            <a href="/team/departments" class="list-group-item on">Departamentos</a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10">
      <div class="panel panel-default table-responsive">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
            </div>
          </div>
        </div>
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th>Departamento</th>
                <th><i class="fa fa-cogs"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($departments as $d): ?>
                <tr data-searchable >
                    <td><?php echo $d->department; ?></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-ajax="/team/department/modify/<?php echo $d->_ ;?>">
                          <span class="fa fa-pencil"></span>
                          Editar
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-ajax="/team/department/remove/<?php echo $d->_ ;?>">
                          <span class="fa fa-close"></span>
                          Remover
                        </button>
                      </div>
                    </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

      </div>
    </div>
  </div>

</div>
<div id="modal-results"></div>
