<div class="warper container-fluid">

  <div class="page-header">
    <h1>Gerenciamento de Equipe</h1>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div role="alert" class="alert fade in hidden">
        <button data-dismiss="alert" class="close" type="button"><span aria-hidden="true">×</span><span class="sr-only">Close</span></button>
        <h4 id="title"></h4>
        <p id="desc"></p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-2">
      <button type="button" class="btn btn-success btn-block btn-circle" data-toggle="modal" data-ajax="/team/create">
        <span class="fa fa-plus"></span> Adicionar Membro
      </button>
      <hr class="dotted">
      <div class="panel panel-default">
        <div class="panel-heading clean">Navegação</div>
        <div class="panel-body no-padd">
          <div class="list-group no-margn mail-nav">
            <a href="/team" class="list-group-item on">Membros Cadastrados</a>
            <a href="/team/departments" class="list-group-item">Departamentos</a>
          </div>
        </div>
      </div>
    </div>

    <div class="col-md-10">
      <div class="panel panel-default table-responsive">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <input type="text" name="search" class="form-control form-control-circle" placeholder="Filtro" data-search >
            </div>
          </div>
        </div>
        <table class="table table-striped no-margn">
            <thead>
              <tr>
                <th class="avtar"></th>
                <th>Nome Completo</th>
                <th>Departamento</th>
                <th>Email</th>
                <th>Telefone</th>
                <th><i class="fa fa-cogs"></i></th>
              </tr>
            </thead>
            <tbody>
              <?php foreach ($members as $member): ?>
                <tr data-searchable >
                    <td><img src="/assets/manager/images/avtar/<?php echo $member->image ?: 'placeholder.jpg'; ?>" alt="<?php echo $member->name; ?>" class="img-circle avtar" /></td>
                    <td><?php echo $member->name; ?></td>
                    <td><?php echo $member->department; ?></td>
                    <td><?php echo $member->email; ?></td>
                    <td><?php echo $member->phone; ?></td>
                    <td>
                      <div class="btn-group">
                        <button type="button" class="btn btn-info" data-toggle="modal" data-ajax="/team/view/<?php echo $member->uid ;?>">
                          <span class="fa fa-info-circle"></span>
                          Info
                        </button>
                        <button type="button" class="btn btn-primary" data-toggle="modal" data-ajax="/team/modify/<?php echo $member->uid ;?>">
                          <span class="fa fa-pencil"></span>
                          Editar
                        </button>
                        <button type="button" class="btn btn-danger" data-toggle="modal" data-ajax="/team/remove/<?php echo $member->uid ;?>">
                          <span class="fa fa-close"></span>
                          Remover
                        </button>
                      </div>
                    </td>
                </tr>
              <?php endforeach; ?>
            </tbody>
          </table>

      </div>
    </div>

  </div>
</div>

<div id="modal-results"></div>
