<div class="warper container-fluid">

    <div class="page-header">
      <h1>Visão Geral</h1>
    </div>

    <div class="row">

      <div class="col-md-3 col-sm-6">
      	<div class="panel panel-default stats rounded">
          	<i class="fa fa-check-square-o bg-danger stats-icon"></i>
              <h3><?php echo $tasks; ?><small class="text-green">8%</small></h3>
              <p class="text-muted">Tarefas em Aberto</p>
          </div>
      </div>

      <div class="col-md-3 col-sm-6">
      	<div class="panel panel-default stats rounded">
          	<i class="fa fa-briefcase bg-danger stats-icon"></i>
              <h3><?php echo $clients; ?></h3>
              <p class="text-muted">Clientes Cadastrados</p>
          </div>
      </div>

      <div class="col-md-3 col-sm-6">
      	<div class="panel panel-default stats rounded">
          	<i class="fa fa-ticket bg-danger stats-icon"></i>
              <h3>02 <small class="text-green">8%</small></h3>
              <p class="text-muted">Chamados em Aberto</p>
          </div>
      </div>

      <div class="col-md-3 col-sm-6">
      	<div class="panel panel-default stats rounded">
          	<i class="fa fa-archive bg-danger stats-icon"></i>
              <h3>02 <small class="text-green">8%</small></h3>
              <p class="text-muted">Projetos em Aberto</p>
          </div>
      </div>

    </div>

    <div class="row">
      <div class="col-md-6">
        <div class="panel panel-default" id="activities">
          <div class="panel-body">
            <ul class="activities-list list-unstyled nicescroll">
              <?php
              foreach($logs as $log):
                switch ($log->action) {
                  case $this->logs->create : $cl = "success-activity"; break;
                  case $this->logs->update : $cl = "warning-activity"; break;
                  case $this->logs->delete : $cl = "danger-activity"; break;
                  case $this->logs->info   : $cl = "info-activity"; break;
                }
              ?>
                <li class="<?php echo $cl; ?>">
                    <span class="time"><?php echo (new \Datetime($log->date))->format("d-m-Y \a\s H:i:s"); ?></span>
                      <p><a href="#"><?php echo $log->name; ?></a> <?php echo $log->description; ?></p>
                  </li>
                <?php endforeach; ?>

              </ul>
          </div>
        </div>
      </div>
      <div class="col-md-6">

        <div class="panel panel-default" data-ng-controller="TodoCtrl">
            <div class="panel-heading un-bold"><h4>Anotações <a href="" data-ng-click="remove()" class="pull-right"><small>Apagar Selecionados</small></a></h4></div>
              <div class="panel-body">
               <ul class="list-group no-margn nicescroll todo-list" style="height:205px; overflow:auto;">
                  <li data-ng-repeat="todo in todos" class="list-group-item">
                  <label class="cr-styled">
                    <input type="checkbox" data-ng-model="todo.done">
                      <i class="fa"></i>
                  </label>
                  <span class="done-{{todo.done}}">{{todo.text}}</span>
                  </li>
               </ul>
              </div>

              <div class="panel-footer">
                  <form data-ng-submit="addTodo()" role="form">
                  <div class="input-group">
                    <input type="text" data-ng-model="todoText" class="form-control" placeholder="add new todo here">
                    <span class="input-group-btn">
                      <button class="btn-primary btn" type="submit" >Add</button>
                    </span>
                  </div>
                  </form>
              </div>


          </div>

      </div>
    </div>

</div>
