<div class="warper container-fluid">

    <div class="page-header">
      <h1>Atividades Recentes</h1>
    </div>

    <div class="panel panel-default" id="activities">
        <div class="panel-body">
          <ul class="activities-list list-unstyled nicescroll">
            <?php
            foreach($logs as $log):
              switch ($log->action) {
                case $this->logs->create : $cl = "success-activity"; break;
                case $this->logs->update : $cl = "warning-activity"; break;
                case $this->logs->delete : $cl = "danger-activity"; break;
                case $this->logs->info   : $cl = "info-activity"; break;
              }
            ?>
              <li class="<?php echo $cl; ?>">
                  <span class="time"><?php echo (new \Datetime($log->date))->format("d-m-Y \a\s H:i:s"); ?></span>
                    <p><a href="#"><?php echo $log->name; ?></a> <?php echo $log->description; ?></p>
                </li>
              <?php endforeach; ?>

            </ul>
        </div>

    </div>

</div>
