<div class="container login">
  <div class="row">
    <div class="col-lg-4 col-lg-offset-4">

      <h3 class="text-center">CRM</h3>
        <p class="text-center">Acesse Painel de Gerenciamento</p>
        <hr class="clean">

        <div class="alert alert-dismissible hidden" role="alert">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <strong id="title"></strong> <br>
          <span id="descr"></span>
        </div>

        <form action="/login/auth" method="post" accept-charset="utf8"  class="validator-form" novalidate="novalidate">
          <?php echo $form->render("security"); ?>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
            <?php echo $form->render("username"); ?>
          </div>
          <div class="form-group input-group">
            <span class="input-group-addon"><i class="fa fa-key"></i></span>
            <?php echo $form->render("password"); ?>
          </div>
          <button type="submit" class="btn btn-purple btn-block">Acessar</button>
        </form>

      </div>
    </div>
</div>
