<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta name="description" content="Metacon Engenharia">
    <meta name="author" content="Hudson Nicoletti">
    <meta name="keywords" content=""/>
    <meta name="robots" content="index, follow">

    <title> Rhino - Project Manager </title>

    <link rel="shortcut icon" href="/favicon.ico">

		<?php echo $this->assets->outputCss(); ?>

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
  </head>
  <body data-ng-app >

    <?php if($this->router->getControllerName() != 'login'): ?>
    <aside class="left-panel">

      <div class="user text-center">
            <img src="/assets/manager/images/avtar/<?php echo $uinfo->image; ?>" class="img-circle" alt="...">
            <h4 class="user-name"><?php echo (@$uinfo->name ? @$uinfo->name : @$uinfo->firstname); ?></h4>

            <div class="dropdown user-login">
              <a href="/login/logout">
                <button class="btn btn-xs dropdown-toggle btn-rounded" type="button" aria-expanded="true">
                  <i class="fa fa-circle status-icon signout"></i> Encerrar Sessão
                </button>
              </a>
            </div>
      </div>

      <nav class="navigation">
        <ul class="list-unstyled">

          <?php echo $navigation; ?>

        </ul>
      </nav>

  </aside>

    <section class="content">
      <header class="top-head container-fluid visible-xs visible-sm">
        <button type="button" class="navbar-toggle pull-left">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </header>

      <?php echo $this->getContent(); ?>

      <footer class="container-fluid footer">
        Copyright &copy; 2016
        <a href="#" target="_blank">Rhino - Project Manager</a>
        <a href="#" class="pull-right scrollToTop"><i class="fa fa-chevron-up"></i></a>
      </footer>

    </section>

    <?php else:?>
      <?php echo $this->getContent(); ?>
    <?php endif;?>

		<?php echo $this->assets->outputJs(); ?>

  </body>
</html>
